export const GET_CONTENIDO_PODCAST = 'GET_CONTENIDO_PODCAST'
export const GET_CONTENIDO_VIDEOCLIP = 'GET_CONTENIDO_VIDEOCLIP'
export const GET_CONTENIDO_DIRECTING = 'GET_CONTENIDO_DIRECTING'
export const GET_CONTENIDO_CINEMA = 'GET_CONTENIDO_CINEMA'